---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git

- name: dotnet-test
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}
- name dotnet-pipeline
  type: git
  source: 
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: pipeline
    username: {{github-username}}
    password: {{github-password}}


   
jobs:
- name: job-pass-files
  public: true
  plan:
  - get: dotnet-test
  - task: create-some-files
    file: dotnet-test/concourse-tutorial/create_some_files.yml
  - put: dotnet-pipeline
    params: {repository: dotnet-test}

- name: job-read-files
  public: true
  plan:
  - get: dotnet-test
    passed: [job-pass-files]
  - task: build
    file: dotnet-test/concourse-tutorial/show_files.yml


