:general:
  date_template: "%Y-%m-%d"

:templates:
  - { location: templates/default_id_report.md, output: ids.md }

:task_systems:
  -
    :name: none
    :regex:
      - { pattern: 'PAC\-(\d+)', label: none }

:vcs:
  :type: git
  :repo_location: '.'
