jobs:
- name: create-release-image
  public: true
  plan:
  - get: repository
    trigger: true
  - put: release-docker-image
    params:
      build: repository

- name: kubernetes-deploy
  public: true
  plan:
  - get: repository
  - get: release-docker-image
    passed: [create-release-image]
  - put: kubernetes
    params:
      image_name: repository/kubernetes-docker-repo
      image_tag: repository/kubernetes-docker-tag

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource

resources:
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: release-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

- name: kubernetes
  type: kubernetes
  source:
    cluster_url: https://http://192.168.99.100:8443
    namespace: default
    cluster_ca: |
      -----BEGIN CERTIFICATE-----
      MIICzjCCAbagAwIBAgIRAP7rjvtxD0o8COkY679aSnkwDQYJKoZIhvcNAQELBQAw
      EDEOMAwGA1UEChMFZGF2aWQwHhcNMTYxMjAyMTEyNjAwWhcNMTkxMTE3MTEyNjAw
      WjAQMQ4wDAYDVQQKEwVkYXZpZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
      ggEBAMUCAHa8YQLWJ83T9dJhwRUCIan/wP+GsTTd0BNuupI0hi8aAvbqNX7bMm85
      chrewAkuJ3eR8cFsbaPbIBCQrV9tyWO7WXZEoQasa0/BcWNWS7Qa0yh1Ggdy0gsu
      tlHBnp5/NhsMU8A/zloRF6uu3BTmkhD5kOHtvZNvumqw59G9PtI4EdvLrL9KKNeE
      ExfXjeGuvpdzbb9FHiyh1j/u6Ww3xkDrhMEUWAGYrE6Nrp/+ns++K3sPNVV0jrz6
      5WHuOzvoJXTKFXGE5japMgKmLyn3SAH28Utg2PKXCS8Q9WnLLMF5Y8Qu/3xLT7vp
      w7mDCygnF79UUKfNuAyqSnwAzCMCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKsMA8G
      A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBADUNkbiazv51GAkVah9U
      Krx2F8GvCBy/gxvWijym3orSGw8beZYM7hnHa9YPro1Mo0wojIENdl9qqbatH3ax
      9jPMFl1uNeDC1KXcikg3Zq3LaMjQMRxS82skKvVroytao4cy7JvBpQXeaYGqKgHm
      S81o1I3e3Fhn6ytbovYc+Od+k59+25fRyk2702L3iw/zzwtAAz8eHTn1fQ3kMj8U
      afmXfkUhkIBjlBm4Uzl9yjbIyDCLMFKiLXNyGAc1kdI55dnBIeCtndQ8/Fx/QYmB
      8XzgaYmO/B9YHVqS06eZMZDBA7udDtQiXLfhiSkPFc+5LNqIv3adg8RVHBkX+kc8
      SWg=
      -----END CERTIFICATE-----
    admin_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEA4yqF1PLvMMK/uq4R5IpmuEn8Lvh8PHAoJdU3IZLcRz4Q3lOa
      6d/yKVMxfEdiVZ+vWKx3U8B4qKUu24RQ1NpXIIrbSor2hp89fwJzTtymNshOH3cP
      2UiLt5Dz5cBrgwDZT7ilCngvAtq/byPd3FKHjrcBJioX8RWbJpU1k1IkuqE6gYSk
      cUlmslb55c1ZjS539kM2LluxOb7ZBq7If0NPDt3XBUN9H5J5UXuAOaKlwMZa/Es8
      OVLJeGdU8RUwaXhF8qhmeKsbmZWTc+hojXmm13Rba/c3uKq0ufkoukN6xp3PWC3r
      Q5W+Glbvr00g/5iWeEP5OBJmHNy69kEHeww6jQIDAQABAoIBAA1MxwshsglbzZfj
      ax7DT6JIiqBBYhyzwFX+trybeZQeOSSbJn2849OxkDsjfslekQiTCGV55laRXT3y
      8DyWD/XSy2YA3tAg8JvIC/I5Du40KgbDlMT2718u+GiiLGk+GnsFZ3xGbxIutniO
      VAX7Ov6LDmEqo740sqG+qKVYcNgQTjhzINI5N+SuHmrVMwmaCj5IGUxneug9Eas2
      Fd0aA5CBkrv5R/+MFT/rssYyTLkGpBr7Ihgmm8dds/0eGCD0m0hF2fc/qwy1BoZK
      E6MQASt5IVxo+Y74F07q4A2iaerxgpEySaPTa+BwzxCCdipGnZI2hCmy+e0P3XHu
      XkctJOECgYEA+Yo4Tj21IKNnvX8yRePvGfirOvTyA+fZKAbj5fYz6cEjHLFEN5g9
      sgem8YxUd3kFmpmjzNetix4Limu16BeEjwnlDiC5W7pL9yHxfjI7uKGDavtrtE1c
      SJW1R7qRILblplt0TEydePve5lKjfcbYrCapYs49IobLTOmVSFhc5/kCgYEA6QwG
      Q5A/u7C6Dfe+pYWMPM9VsN2wceRpzQCcCxaDG76s1ZRhN3ZhEXq9F7lxevwz91H1
      W4wIICGMeN6Awkdcg4s24thV8PPD5AWZHR7Ae9KkweaMUOqyJgUHTNlecw6fktKi
      nSfe3rcCT5h5a+3n49vFy9c+Gq9eUqREuAbm1DUCgYAgjxdPph+G9asof3sowVfG
      NLrqw2D8f3jHDzcXHyug2VFiggKbmmKaYwM2SxAOUp0XkepcZNvA5hetZOZkNQVX
      wHvBfyWQQVt+EFC5HYbLTU+fWtSvvtRGqDnx9PbQpOyL6yzec7SsP3jS5n9sftBw
      jc7WFIDHi3zlOSkAOn9MyQKBgGfxvA2Allyxy5qVSMxtD4rD83WKu7tg5KvSPMdZ
      SCsk1dQBdYcWXt87/oFJbksrmEYUoTou8CTcsdnrbES7LZFik52EXni1UUcwFAYA
      BFx2LJRrr2Qb+k+o6IOnZFAvUo9bMbqk4Ow3dmloGahBGa/xA30SyRl/5LM5n4jx
      Ux2NAoGATkHkQTo/RtCan0XuNU7EH3qyOxgWSKoH93O9FHubVOiZIsptkAOxXJpb
      s5TNvFupR9Lznmg3sECrGKj2RSETj4tJQHjYLltrInypkm4IRSvEs+Zo5B/4lKkq
      WCucnJj94/oVxWyPV8tThkjL6n93vyrlfIu1U3UJzrDhmLurhRU=
      -----END RSA PRIVATE KEY-----
    admin_cert: |
      -----BEGIN CERTIFICATE-----
      MIIDWTCCAkGgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTE2MTIxOTA4NTQzOVoXDTE3MTIxOTA4NTQzOVowEzERMA8GA1UE
      AxMIbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDjKoXU
      8u8wwr+6rhHkima4Sfwu+Hw8cCgl1TchktxHPhDeU5rp3/IpUzF8R2JVn69YrHdT
      wHiopS7bhFDU2lcgittKivaGnz1/AnNO3KY2yE4fdw/ZSIu3kPPlwGuDANlPuKUK
      eC8C2r9vI93cUoeOtwEmKhfxFZsmlTWTUiS6oTqBhKRxSWayVvnlzVmNLnf2QzYu
      W7E5vtkGrsh/Q08O3dcFQ30fknlRe4A5oqXAxlr8Szw5Usl4Z1TxFTBpeEXyqGZ4
      qxuZlZNz6GiNeabXdFtr9ze4qrS5+Si6Q3rGnc9YLetDlb4aVu+vTSD/mJZ4Q/k4
      EmYc3Lr2QQd7DDqNAgMBAAGjgbUwgbIwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
      MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMHMGA1UdEQRsMGqC
      JGt1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbIIWa3ViZXJuZXRl
      cy5kZWZhdWx0LnN2Y4ISa3ViZXJuZXRlcy5kZWZhdWx0ggprdWJlcm5ldGVzhwTA
      qGNkhwQKAAABMA0GCSqGSIb3DQEBCwUAA4IBAQBo0pkCnHdB/RAIAZFAr+Ig2fBo
      6j4ImEB/osNKbUTtjOasGAO9KrIKSLThYVSxEoOL+cR+AlK8aeOpZ5O9tSuIIC9C
      qT645CyZlJoPjMRHEth2O1bXmX84GaOMMgX3CY/ZxPmhbKmb1ra+RtVTrQguvcO1
      IZWIR/fxKFkmhD2+co+fKaBK/Y70jZyv0E/Nh9IUvBPmE37YdWuWOEhBqzMZCYve
      3xoYFEjRWYOI/2l+urfflTM81cHRi7DUu2KqjXnsurkVrg46x5nB/BSg0aGWa+b7
      8vOTjSf6TQWmYN7QlJzNXzqd4XP/fyRlezqjUflS31qZpC59iPz60wcQzPxG
      -----END CERTIFICATE-----
    resource_type: deployment
    resource_name: some_pod_name
