jobs:
- name: create-release-image
  public: true
  plan:
  - get: repository
    trigger: true
  - put: release-docker-image
    params:
      build: repository

- name: kubernetes-deploy
  public: true
  plan:
  - get: repository
  - get: release-docker-image
    passed: [create-release-image]
  - put: kubernetes
    params:
      image_name: repository/kubernetes-docker-repo
      image_tag: repository/kubernetes-docker-tag

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource

resources:
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: release-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

- name: kubernetes
  type: kubernetes
  source:
    cluster_url: https://http://192.168.99.100:8443
    namespace: default
    cluster_ca: |
      -----BEGIN CERTIFICATE-----
      MIICzjCCAbagAwIBAgIRAP7rjvtxD0o8COkY679aSnkwDQYJKoZIhvcNAQELBQAw
      EDEOMAwGA1UEChMFZGF2aWQwHhcNMTYxMjAyMTEyNjAwWhcNMTkxMTE3MTEyNjAw
      WjAQMQ4wDAYDVQQKEwVkYXZpZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
      ggEBAMUCAHa8YQLWJ83T9dJhwRUCIan/wP+GsTTd0BNuupI0hi8aAvbqNX7bMm85
      chrewAkuJ3eR8cFsbaPbIBCQrV9tyWO7WXZEoQasa0/BcWNWS7Qa0yh1Ggdy0gsu
      tlHBnp5/NhsMU8A/zloRF6uu3BTmkhD5kOHtvZNvumqw59G9PtI4EdvLrL9KKNeE
      ExfXjeGuvpdzbb9FHiyh1j/u6Ww3xkDrhMEUWAGYrE6Nrp/+ns++K3sPNVV0jrz6
      5WHuOzvoJXTKFXGE5japMgKmLyn3SAH28Utg2PKXCS8Q9WnLLMF5Y8Qu/3xLT7vp
      w7mDCygnF79UUKfNuAyqSnwAzCMCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKsMA8G
      A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBADUNkbiazv51GAkVah9U
      Krx2F8GvCBy/gxvWijym3orSGw8beZYM7hnHa9YPro1Mo0wojIENdl9qqbatH3ax
      9jPMFl1uNeDC1KXcikg3Zq3LaMjQMRxS82skKvVroytao4cy7JvBpQXeaYGqKgHm
      S81o1I3e3Fhn6ytbovYc+Od+k59+25fRyk2702L3iw/zzwtAAz8eHTn1fQ3kMj8U
      afmXfkUhkIBjlBm4Uzl9yjbIyDCLMFKiLXNyGAc1kdI55dnBIeCtndQ8/Fx/QYmB
      8XzgaYmO/B9YHVqS06eZMZDBA7udDtQiXLfhiSkPFc+5LNqIv3adg8RVHBkX+kc8
      SWg=
      -----END CERTIFICATE-----
    resource_type: deployment
    resource_name: some_pod_name
