resources:
- name: dotnet-test
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git

- name: hello-world-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

jobs:
- name: restore-build 
  public: true
  plan:
  - get: dotnet-test
  - put: dotnetbuild
    params:
      build: dotnet-test

- name: unittest
  public: true
  plan:
  - get: dotnet-test
    passed: [restore-build]
  - task: build
    file: dotnet-test/build/dotnet-build.yml

