resources:
- name: dotnet-test
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git


jobs:
- name: restore 
  public: true
  plan:
  - get: dotnet-test
  - task: restore
    file: dotnet-test/build/dotnet-restore.yml

- name: build 
  public: true
  plan:
  - get: dotnet-test
    passed: [restore]
  - task: build
    file: dotnet-test/build/dotnet-build.yml

