resources:
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: release-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

jobs:
- name: create-release-image
  public: true
  plan:
  - get: repository
    trigger: true
  - put: release-docker-image
    params:
      build: repository

#- name: unit-test
#  public: true
#  plan:
#  - get: dotnet-test
#  - get: dotnet-pipeline
#    passed: [restore]
#  - task: test
#    file: dotnet-test/build/build-job.yml
#  - put: dotnet-pipeline
#    params: {repository: build}
