jobs:
- name: create-release-image
  public: true
  plan:
  - get: repository
    trigger: true
  - put: release-docker-image
    params:
      build: repository

- name: kubernetes-deploy
  public: true
  plan:
  - get: repository
  - get: release-docker-image
    passed: [create-release-image]
  - put: kubernetes
    params:
      image_name: repository/deploy-kubernetes/kubernetes-docker-repo
      image_tag: repository/deploy-kubernetes/kubernetes-docker-tag

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource

resources:
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: release-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

- name: kubernetes
  type: kubernetes
  source:
    cluster_url: https://http://192.168.99.100:8443
    namespace: default
    cluster_ca: TUlJQ3pqQ0NBYmFnQXdJQkFnSVJBUDdyanZ0eEQwbzhDT2tZNjc5YVNua3dEUVlKS29aSWh2Y05BUUVMQlFBdw0KRURFT01Bd0dBMVVFQ2hNRlpHRjJhV1F3SGhjTk1UWXhNakF5TVRFeU5qQXdXaGNOTVRreE1URTNNVEV5TmpBdw0KV2pBUU1RNHdEQVlEVlFRS0V3VmtZWFpwWkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQw0KZ2dFQkFNVUNBSGE4WVFMV0o4M1Q5ZEpod1JVQ0lhbi93UCtHc1RUZDBCTnV1cEkwaGk4YUF2YnFOWDdiTW04NQ0KY2hyZXdBa3VKM2VSOGNGc2JhUGJJQkNRclY5dHlXTzdXWFpFb1Fhc2EwL0JjV05XUzdRYTB5aDFHZ2R5MGdzdQ0KdGxIQm5wNS9OaHNNVThBL3psb1JGNnV1M0JUbWtoRDVrT0h0dlpOdnVtcXc1OUc5UHRJNEVkdkxyTDlLS05lRQ0KRXhmWGplR3V2cGR6YmI5RkhpeWgxai91Nld3M3hrRHJoTUVVV0FHWXJFNk5ycC8rbnMrK0szc1BOVlYwanJ6Ng0KNVdIdU96dm9KWFRLRlhHRTVqYXBNZ0ttTHluM1NBSDI4VXRnMlBLWENTOFE5V25MTE1GNVk4UXUvM3hMVDd2cA0KdzdtREN5Z25GNzlVVUtmTnVBeXFTbndBekNNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tzTUE4Rw0KQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRFVOa2JpYXp2NTFHQWtWYWg5VQ0KS3J4MkY4R3ZDQnkvZ3h2V2lqeW0zb3JTR3c4YmVaWU03aG5IYTlZUHJvMU1vMHdvaklFTmRsOXFxYmF0SDNheA0KOWpQTUZsMXVOZURDMUtYY2lrZzNacTNMYU1qUU1SeFM4MnNrS3ZWcm95dGFvNGN5N0p2QnBRWGVhWUdxS2dIbQ0KUzgxbzFJM2UzRmhuNnl0Ym92WWMrT2QrazU5KzI1ZlJ5azI3MDJMM2l3L3p6d3RBQXo4ZUhUbjFmUTNrTWo4VQ0KYWZtWGZrVWhrSUJqbEJtNFV6bDl5amJJeURDTE1GS2lMWE55R0FjMWtkSTU1ZG5CSWVDdG5kUTgvRngvUVltQg0KOFh6Z2FZbU8vQjlZSFZxUzA2ZVpNWkRCQTd1ZER0UWlYTGZoaVNrUEZjKzVMTnFJdjNhZGc4UlZIQmtYK2tjOA0KU1dnPQ0K
    admin_key: TUlJRW9nSUJBQUtDQVFFQTR5cUYxUEx2TU1LL3VxNFI1SXBtdUVuOEx2aDhQSEFvSmRVM0laTGNSejRRM2xPYQ0KNmQveUtWTXhmRWRpVlordldLeDNVOEI0cUtVdTI0UlExTnBYSUlyYlNvcjJocDg5ZndKelR0eW1Oc2hPSDNjUA0KMlVpTHQ1RHo1Y0JyZ3dEWlQ3aWxDbmd2QXRxL2J5UGQzRktIanJjQkppb1g4UldiSnBVMWsxSWt1cUU2Z1lTaw0KY1VsbXNsYjU1YzFaalM1MzlrTTJMbHV4T2I3WkJxN0lmME5QRHQzWEJVTjlINUo1VVh1QU9hS2x3TVphL0VzOA0KT1ZMSmVHZFU4UlV3YVhoRjhxaG1lS3NibVpXVGMraG9qWG1tMTNSYmEvYzN1S3EwdWZrb3VrTjZ4cDNQV0Mzcg0KUTVXK0dsYnZyMDBnLzVpV2VFUDVPQkptSE55NjlrRUhld3c2alFJREFRQUJBb0lCQUExTXh3c2hzZ2xielpmag0KYXg3RFQ2SklpcUJCWWh5endGWCt0cnliZVpRZU9TU2JKbjI4NDlPeGtEc2pmc2xla1FpVENHVjU1bGFSWFQzeQ0KOER5V0QvWFN5MllBM3RBZzhKdklDL0k1RHU0MEtnYkRsTVQyNzE4dStHaWlMR2srR25zRlozeEdieEl1dG5pTw0KVkFYN092NkxEbUVxbzc0MHNxRytxS1ZZY05nUVRqaHpJTkk1TitTdUhtclZNd21hQ2o1SUdVeG5ldWc5RWFzMg0KRmQwYUE1Q0JrcnY1Ui8rTUZUL3Jzc1l5VExrR3BCcjdJaGdtbThkZHMvMGVHQ0QwbTBoRjJmYy9xd3kxQm9aSw0KRTZNUUFTdDVJVnhvK1k3NEYwN3E0QTJpYWVyeGdwRXlTYVBUYStCd3p4Q0NkaXBHblpJMmhDbXkrZTBQM1hIdQ0KWGtjdEpPRUNnWUVBK1lvNFRqMjFJS05udlg4eVJlUHZHZmlyT3ZUeUErZlpLQWJqNWZZejZjRWpITEZFTjVnOQ0Kc2dlbThZeFVkM2tGbXBtanpOZXRpeDRMaW11MTZCZUVqd25sRGlDNVc3cEw5eUh4ZmpJN3VLR0RhdnRydEUxYw0KU0pXMVI3cVJJTGJscGx0MFRFeWRlUHZlNWxLamZjYllyQ2FwWXM0OUlvYkxUT21WU0ZoYzUva0NnWUVBNlF3Rw0KUTVBL3U3QzZEZmUrcFlXTVBNOVZzTjJ3Y2VScHpRQ2NDeGFERzc2czFaUmhOM1poRVhxOUY3bHhldnd6OTFIMQ0KVzR3SUlDR01lTjZBd2tkY2c0czI0dGhWOFBQRDVBV1pIUjdBZTlLa3dlYU1VT3F5SmdVSFRObGVjdzZma3RLaQ0KblNmZTNyY0NUNWg1YSszbjQ5dkZ5OWMrR3E5ZVVxUkV1QWJtMURVQ2dZQWdqeGRQcGgrRzlhc29mM3Nvd1ZmRw0KTkxycXcyRDhmM2pIRHpjWEh5dWcyVkZpZ2dLYm1tS2FZd00yU3hBT1VwMFhrZXBjWk52QTVoZXRaT1prTlFWWA0Kd0h2QmZ5V1FRVnQrRUZDNUhZYkxUVStmV3RTdnZ0UkdxRG54OVBiUXBPeUw2eXplYzdTc1AzalM1bjlzZnRCdw0KamM3V0ZJREhpM3psT1NrQU9uOU15UUtCZ0dmeHZBMkFsbHl4eTVxVlNNeHRENHJEODNXS3U3dGc1S3ZTUE1kWg0KU0NzazFkUUJkWWNXWHQ4Ny9vRkpia3NybUVZVW9Ub3U4Q1Rjc2RucmJFUzdMWkZpazUyRVhuaTFVVWN3RkFZQQ0KQkZ4MkxKUnJyMlFiK2srbzZJT25aRkF2VW85Yk1icWs0T3czZG1sb0dhaEJHYS94QTMwU3lSbC81TE01bjRqeA0KVXgyTkFvR0FUa0hrUVRvL1J0Q2FuMFh1TlU3RUgzcXlPeGdXU0tvSDkzTzlGSHViVk9pWklzcHRrQU94WEpwYg0KczVUTnZGdXBSOUx6bm1nM3NFQ3JHS2oyUlNFVGo0dEpRSGpZTGx0cklueXBrbTRJUlN2RXMrWm81Qi80bEtrcQ0KV0N1Y25Kajk0L29WeFd5UFY4dFRoa2pMNm45M3Z5cmxmSXUxVTNVSnpyRGhtTHVyaFJVPQ==
    admin_cert: TUlJRFdUQ0NBa0dnQXdJQkFnSUJBakFOQmdrcWhraUc5dzBCQVFzRkFEQVZNUk13RVFZRFZRUURFd3B0YVc1cA0KYTNWaVpVTkJNQjRYRFRFMk1USXhPVEE0TlRRek9Wb1hEVEUzTVRJeE9UQTROVFF6T1Zvd0V6RVJNQThHQTFVRQ0KQXhNSWJXbHVhV3QxWW1Vd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURqS29YVQ0KOHU4d3dyKzZyaEhraW1hNFNmd3UrSHc4Y0NnbDFUY2hrdHhIUGhEZVU1cnAzL0lwVXpGOFIySlZuNjlZckhkVA0Kd0hpb3BTN2JoRkRVMmxjZ2l0dEtpdmFHbnoxL0FuTk8zS1kyeUU0ZmR3L1pTSXUza1BQbHdHdURBTmxQdUtVSw0KZUM4QzJyOXZJOTNjVW9lT3R3RW1LaGZ4RlpzbWxUV1RVaVM2b1RxQmhLUnhTV2F5VnZubHpWbU5MbmYyUXpZdQ0KVzdFNXZ0a0dyc2gvUTA4TzNkY0ZRMzBma25sUmU0QTVvcVhBeGxyOFN6dzVVc2w0WjFUeEZUQnBlRVh5cUdaNA0KcXh1WmxaTno2R2lOZWFiWGRGdHI5emU0cXJTNStTaTZRM3JHbmM5WUxldERsYjRhVnUrdlRTRC9tSlo0US9rNA0KRW1ZYzNMcjJRUWQ3RERxTkFnTUJBQUdqZ2JVd2diSXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRVw0KTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUhNR0ExVWRFUVJzTUdxQw0KSkd0MVltVnlibVYwWlhNdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYklJV2EzVmlaWEp1WlhSbA0KY3k1a1pXWmhkV3gwTG5OMlk0SVNhM1ZpWlhKdVpYUmxjeTVrWldaaGRXeDBnZ3ByZFdKbGNtNWxkR1Z6aHdUQQ0KcUdOa2h3UUtBQUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCbzBwa0NuSGRCL1JBSUFaRkFyK0lnMmZCbw0KNmo0SW1FQi9vc05LYlVUdGpPYXNHQU85S3JJS1NMVGhZVlN4RW9PTCtjUitBbEs4YWVPcFo1Tzl0U3VJSUM5Qw0KcVQ2NDVDeVpsSm9Qak1SSEV0aDJPMWJYbVg4NEdhT01NZ1gzQ1kvWnhQbWhiS21iMXJhK1J0VlRyUWd1dmNPMQ0KSVpXSVIvZnhLRmttaEQyK2NvK2ZLYUJLL1k3MGpaeXYwRS9OaDlJVXZCUG1FMzdZZFd1V09FaEJxek1aQ1l2ZQ0KM3hvWUZFalJXWU9JLzJsK3VyZmZsVE04MWNIUmk3RFV1Mktxalhuc3Vya1ZyZzQ2eDVuQi9CU2cwYUdXYStiNw0KOHZPVGpTZjZUUVdtWU43UWxKek5YenFkNFhQL2Z5UmxlenFqVWZsUzMxcVpwQzU5aVB6NjB3Y1F6UHhH
    resource_type: deployment
    resource_name: some_pod_name
