jobs:
- name: wincrement-version
  public: true
  plan: 
  - get: version
  - get: repository
    trigger: true
  - task: version
    file: repository/versioning/wincrementor.yml
  - put: version
    params: {file: wincrementor/wincrement-version}

- name: create-documentation
  public: true
  plan: 
  - get: repository
  - get: version
    passed: [wincrement-version]
  - task: copy-repository
    file: repository/documentation/copy-repository.yml
  - put: documentation-container
    params: 
      build: repository/documentation
      tag: version/version
      tag_as_latest: true

- name: pac-release-notes
  public: true
  plan:
  - get: repository
  - get: version
    passed: [wincrement-version]
  - put: release-notes

- name: create-release-image
  public: true
  plan: 
  - get: repository
  - get: version
    passed: [wincrement-version]
  - aggregate: 
    - put: release-docker-image
      params:
        build: repository 
        tag: version/version
        tag_as_latest: true

- name: kubernetes-deploy-release
  public: true
  plan:
  - get: repository
  - get: version
    passed: [create-release-image]
  - get: release-docker-image
    passed: [create-release-image]
    trigger: true
  - put: kubernetes
    params:
      image_name: repository/deploy-kubernetes/kubernetes-docker-repo
      image_tag: version/number

- name: kubernetes-serve-documentation
  public: true
  plan:
  - get: repository
  - get: version
    passed: [create-documentation]
  - get: documentation-container
    passed: [create-documentation]
    trigger: true
  - put: kubernetes
    params:
      image_name: repository/deploy-kubernetes/kubernetes-docker-repo
      image_tag: version/number

- name: kubernetes-serve-release-notes
  public: true
  plan:
  - get: repository
  - get: version
    passed: [pac-release-notes]
  - get: release-notes
    passed: [pac-release-notes]
    trigger: true
  - put: kubernetes
    params:
      image_name: repository/deploy-kubernetes/kubernetes-docker-repo
      image_tag: version/number


resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource

resources:
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0
    uri: git@github.com:Sharor/concourse-playtime.git
    branch: version
    file: version
    private_key: {{concourse-token}}

- name: release-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

- name: documentation-container
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-documentation-image}}

- name: release-notes
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-release-notes-image}}

- name: kubernetes
  type: kubernetes
  source:
    cluster_url: https://192.168.99.100:8443
    namespace: default
    cluster_ca: {{cluster-ca}}
    admin_key: {{admin-key}}
    admin_cert: {{admin-cert}}
    resource_type: deployment
    resource_name: test
