resources:
- name: ready-branches
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: ready/*
    username: {{github-username}}
    password: {{github-password}}


- name: dotnet-test
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git

- name: dotnet-pipeline
  type: git
  source:
    uri: https://github.com/Sharor/concourse-playtime.git
    branch: pipline
    username: {{github-username}}
    password: {{github-password}}



- name: dotnetbuild
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

jobs:
- name: integration-job
  public: true
  plan:
  - get: dotnet-test
  - get: ready-branches
    trigger: true
  - task: integration
    file: dotnet-test/integration/job-integration.yml

- name: restore
  public: true
  plan:
  - get: dotnet-test
  - task: restore-dotnet
    file: dotnet-test/build/restore-job.yml
  - put: dotnet-pipeline
    params: {repository: restore}

- name: unit-test
  public: true
  plan:
  - get: dotnet-test
  - get: dotnet-pipeline
    passed: [restore]
  - task: test
    file: dotnet-test/build/build-job.yml
  - put: dotnet-pipeline
    params: {repository: build}
